@extends('layouts.app')
@section('title','Admin Dashboard | the sun Agency')
@section('plain') true @endsection
@section('content')
<div class="sidebar-layout">
    <aside class="sidebar"><a href="{{ route('home') }}" class="brand">THE SUN<span>.</span></a><div style="margin-top:28px"><a class="admin-link" href="#overview">📊 Overview</a><a class="admin-link" href="#about">ℹ️ About Page</a><a class="admin-link" href="#services">🛠️ Services</a><a class="admin-link" href="#blogs">📝 Blog</a><a class="admin-link" href="#messages">📩 Messages</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="admin-link" style="width:100%;text-align:left;border:0;background:transparent;color:var(--red)">🚪 Logout</button></form></div></aside>
    <main class="admin-main"><h1 class="grad" style="font-family:Syne,sans-serif;font-size:3rem">Command Center</h1>@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
        <section id="overview" class="section"><div class="grid"><div class="card"><p class="muted">Revenue</p><h2>TZS {{ number_format($revenue) }}</h2></div><div class="card"><p class="muted">Applications</p><h2>{{ $applicationsCount }}</h2></div><div class="card"><p class="muted">Users</p><h2>{{ $usersCount }}</h2></div><div class="card"><p class="muted">Pending Messages</p><h2>{{ $messagesCount }}</h2></div></div></section>
        <section id="about" class="section"><h2>Manage About Page</h2><form class="card form" method="POST" action="{{ route('admin.about.update') }}">@csrf<input class="input" name="hero_title" value="{{ old('hero_title',$about->hero_title ?? '') }}" placeholder="Hero title" required><textarea name="hero_description" required>{{ old('hero_description',$about->hero_description ?? '') }}</textarea><input class="input" name="story_title" value="{{ old('story_title',$about->story_title ?? '') }}" placeholder="Story title" required><textarea name="story_description" required>{{ old('story_description',$about->story_description ?? '') }}</textarea><div class="grid"><input class="input" name="projects_count" type="number" value="{{ old('projects_count',$about->projects_count ?? 500) }}"><input class="input" name="clients_count" type="number" value="{{ old('clients_count',$about->clients_count ?? 150) }}"><input class="input" name="years_count" type="number" value="{{ old('years_count',$about->years_count ?? 10) }}"><input class="input" name="team_count" type="number" value="{{ old('team_count',$about->team_count ?? 25) }}"></div><button class="btn">Save About</button></form></section>
        <section id="services" class="section"><h2>Manage Services</h2><form class="card form" method="POST" action="{{ route('admin.services.store') }}">@csrf<div class="grid"><input class="input" name="icon" placeholder="Icon" required><input class="input" name="title" placeholder="Title" required><input class="input" name="order" type="number" placeholder="Order"></div><textarea name="description" placeholder="Description" required></textarea><button class="btn">Add Service</button></form><div class="grid" style="margin-top:20px">@foreach($services as $service)<div class="card"><h3>{{ $service->icon }} {{ $service->title }}</h3><p class="muted">{{ $service->description }}</p><form method="POST" action="{{ route('admin.services.toggle',$service) }}">@csrf @method('PATCH')<button class="btn ghost">{{ $service->is_active ? 'Disable' : 'Enable' }}</button></form></div>@endforeach</div></section>
        <section id="blogs" class="section"><h2>Manage Blog</h2><form class="card form" method="POST" action="{{ route('admin.blogs.store') }}">@csrf<input class="input" name="title" placeholder="Title" required><div class="grid"><input class="input" name="category" placeholder="Category" required><input class="input" name="author" placeholder="Author" required><input class="input" name="published_at" type="date" required></div><textarea name="content" placeholder="Content" required></textarea><label class="muted"><input type="checkbox" name="is_featured" value="1"> Featured</label><button class="btn">Publish Blog</button></form><table class="table" style="margin-top:20px"><tr><th>Title</th><th>Category</th><th>Date</th></tr>@foreach($blogs as $blog)<tr><td>{{ $blog->title }}</td><td>{{ $blog->category }}</td><td>{{ $blog->published_at->format('M d, Y') }}</td></tr>@endforeach</table></section>
        <section id="messages" class="section"><h2>Messages</h2><table class="table"><tr><th>Name</th><th>Email</th><th>Status</th><th>Action</th></tr>@foreach($messages as $message)<tr><td>{{ $message->name }}</td><td>{{ $message->email }}</td><td>{{ $message->status }}</td><td><form method="POST" action="{{ route('admin.messages.read',$message) }}">@csrf @method('PATCH')<button class="btn ghost">Mark Read</button></form></td></tr>@endforeach</table></section>
    </main>
</div>
@endsection
